# HTTP 代理端口
port: 7890
# SOCKS5 代理端口
socks-port: 7891
# 允许局域网连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局）/ Direct（直连）
mode: Rule
# 日志级别：info / warning / error / debug / silent
log-level: info
# 外部控制接口（用于 Dashboard）
external-controller: 127.0.0.1:9090

# 代理节点定义 (示例)
proxies:
  # - name: "Shadowsocks 示例"
  #   type: ss
  #   server: server
  #   port: 443
  #   cipher: chacha20-ietf-poly1305
  #   password: "password"

  # - name: "Vmess 示例"
  #   type: vmess
  #   server: server
  #   port: 443
  #   uuid: uuid
  #   alterId: 64
  #   cipher: auto

# 代理组定义
proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - DIRECT
      # - "Shadowsocks 示例"

# 规则定义
rules:
  - DOMAIN-SUFFIX,google.com,PROXY
  - DOMAIN-KEYWORD,google,PROXY
  - DOMAIN,google.com,PROXY
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
